POST http://localhost:5000/signup

###

GET http://localhost:3000/login


###

http://localhost:3000/login
Content-Type: application/json

{
    "username": "Dave",
    "password": "Loginer"
}

###

POST http://localhost:5000/signup